/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 building.glb --instance --types 
Files: building.glb [761.37KB] > D:\Kaos\react-threeJS\public\models\building-transformed.glb [47.92KB] (94%)
Author: ModelMaker (https://sketchfab.com/mireubay1)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/game-ready-city-building-2bd7122c0f774cb48565187848154436
Title: Game Ready City Building
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three/examples/jsm/loaders/GLTFLoader.js";
import { InstancedMesh } from "three";

type GLTFResult = GLTF & {
    nodes: {
        Object_4: THREE.Mesh;
        Object_1: InstancedMesh;
        Object_2: InstancedMesh;
        Object_8: InstancedMesh;
        Object_9: InstancedMesh;
        Object_11: InstancedMesh;
        Object_59: InstancedMesh;
    };
    materials: {
        atlas: THREE.MeshStandardMaterial;
    };
};

type ContextType = Record<
    string,
    React.ForwardRefExoticComponent<JSX.IntrinsicElements["mesh"]>
>;

export function BuildingGLB(props: JSX.IntrinsicElements["group"]) {
    const { nodes, materials } = useGLTF(
        "models/building-transformed.glb"
    ) as GLTFResult;
    return (
        <group {...props} dispose={null} scale={[0.35, 0.5, 0.35]}>
            <mesh
                geometry={nodes.Object_4.geometry}
                material={materials.atlas}
                position={[-1.471, -0.225, 0.004]}
                rotation={[Math.PI / 2, 0, 0]}
            />
            <instancedMesh
                args={[nodes.Object_1.geometry, materials.atlas, 8]}
                instanceMatrix={nodes.Object_1.instanceMatrix}
            />
            <instancedMesh
                args={[nodes.Object_2.geometry, materials.atlas, 8]}
                instanceMatrix={nodes.Object_2.instanceMatrix}
            />
            <instancedMesh
                args={[nodes.Object_8.geometry, materials.atlas, 6]}
                instanceMatrix={nodes.Object_8.instanceMatrix}
            />
            <instancedMesh
                args={[nodes.Object_9.geometry, materials.atlas, 8]}
                instanceMatrix={nodes.Object_9.instanceMatrix}
            />
            <instancedMesh
                args={[nodes.Object_11.geometry, materials.atlas, 11]}
                instanceMatrix={nodes.Object_11.instanceMatrix}
            />
            <instancedMesh
                args={[nodes.Object_59.geometry, materials.atlas, 15]}
                instanceMatrix={nodes.Object_59.instanceMatrix}
            />
        </group>
    );
}

useGLTF.preload("models/building-transformed.glb");
